services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile

    image: factory_logic:latest
    container_name: factory_logic_bot

    env_file:
      - .env

    restart: unless-stopped

    init: true

    security_opt:
      - no-new-privileges:true

    command:
      - python
      - -m
      - app.interfaces.max_bot.main